### ISSUE TITLE
Branding of this repo

### ISSUE THREAD

**Issue by foolip** [webcompat/browser-compat-bugs#3]
If we're going to tweet about this repo and ask web developers to file issues, what do we call it? "webdev" doesn't capture that it's about browser compatibility/interoperability issues.

My best suggestion would be "browsercompat" or "browser-compat" which would work as hashtags and as a repo name if we want to rename it.

@jgraham @karlcow WDYT?

**Comment by foolip** [comment]
Treating it as a sibling of https://github.com/webcompat/web-bugs would also suggest the name "browser-bugs", but that suggests a broader scope than we want here. This should really just be a triage mechanism, which result in high-quality bugs filed on the right browser engine.

**Comment by miketaylr** [comment]
"browser-compat" seems catchier than "webdev", or perhaps "browser-compat-bugs" to disambiguate from mdn's "browser-compat-data"

**Comment by jgraham** [comment]
I"m happy with `browser-compat-bugs`.

**Comment by foolip** [comment]
I like "browser-compat-bugs"!

**Comment by karlcow** [comment]
Name has been changed. 
https://github.com/webcompat/browser-compat-bugs/
